import React, { useState, useEffect, useRef, useCallback } from "react";
import { api } from "./api";
import { useAuth } from "./AuthContext";
import Login from "./Login";
import Register from "./Register";

const SECTIONS = [
  { key: "carreira",       label: { pt: "Carreira",       en: "Career"        }, icon: "[+]" },
  { key: "projetos",       label: { pt: "Projetos",       en: "Bills"         }, icon: "[=]" },
  { key: "votacoes",       label: { pt: "Votacoes",       en: "Votes"         }, icon: "[v]" },
  { key: "patrimonio",     label: { pt: "Patrimonio",     en: "Assets"        }, icon: "[$]" },
  { key: "polemicas",      label: { pt: "Polemicas",      en: "Controversies" }, icon: "[!]" },
  { key: "ficha_judicial", label: { pt: "Ficha Judicial", en: "Legal Record"  }, icon: "[J]" },
];

const COUNTRY_FLAGS = {
  BR: "BR", US: "US", IL: "IL", GB: "GB",
  FR: "FR", DE: "DE", AR: "AR", VE: "VE",
  RU: "RU", CN: "CN",
};

const UI_TEXT = {
  pt: {
    eyebrow: "SISTEMA ATIVO",
    title: "Politics",
    titleAccent: "AI",
    subtitle: "Cruzamento de dados publicos com IA",
    placeholder: "Buscar politico por nome ou pais...",
    trending: "Mais buscados hoje",
    sources: "Fontes:",
    model: "Mistral Large - dados publicos",
    loading: "Consultando Mistral AI + Neon DB...",
    emptyTitle: "Busque um politico",
    heroTitle: "Transparencia com IA",
    heroSub: "Busque qualquer politico do mundo e veja carreira, projetos, votacoes, patrimonio e ficha judicial.",
    disclaimer: "Dados gerados por IA com base em informacoes publicas. Verifique sempre nas fontes oficiais.",
    allCountries: "Todos",
    officialLinks: "Consulte nas fontes oficiais",
    officialData: "Dados oficiais cruzados",
    legalFound: "Registros oficiais encontrados",
    cached: "CACHE",
    tokens: "tokens",
  },
  en: {
    eyebrow: "SYSTEM ACTIVE",
    title: "Politics",
    titleAccent: "AI",
    subtitle: "AI-powered public data analysis",
    placeholder: "Search politicians by name or country...",
    trending: "Trending today",
    sources: "Sources:",
    model: "Mistral Large - public data",
    loading: "Querying Mistral AI + Neon DB...",
    emptyTitle: "Search a politician",
    heroTitle: "Transparency with AI",
    heroSub: "Search any politician worldwide and see career, bills, votes, assets and legal record.",
    disclaimer: "Data generated by AI from public records. Always verify at official sources.",
    allCountries: "All",
    officialLinks: "Check official sources",
    officialData: "Official data crossed",
    legalFound: "Official records found",
    cached: "CACHE",
    tokens: "tokens",
  },
};

function useDebounce(value, delay) {
  const [debounced, setDebounced] = useState(value);
  useEffect(() => {
    const t = setTimeout(() => setDebounced(value), delay);
    return () => clearTimeout(t);
  }, [value, delay]);
  return debounced;
}

function TypewriterText({ text, speed = 14, onDone }) {
  const [displayed, setDisplayed] = useState("");
  const [done, setDone] = useState(false);
  const ref = useRef(0);
  useEffect(() => {
    setDisplayed(""); setDone(false); ref.current = 0;
    if (!text) return;
    const iv = setInterval(() => {
      ref.current++;
      setDisplayed(text.slice(0, ref.current));
      if (ref.current >= text.length) { clearInterval(iv); setDone(true); if (onDone) onDone(); }
    }, speed);
    return () => clearInterval(iv);
  }, [text]);
  return <span>{displayed}{!done && <span className="cursor" />}</span>;
}

export default function App() {
  const [lang, setLang]                   = useState("pt");
  const [query, setQuery]                 = useState("");
  const [countryFilter, setCountryFilter] = useState("");
  const [suggestions, setSuggestions]     = useState([]);
  const [trending, setTrending]           = useState([]);
  const [politician, setPolitician]       = useState(null);
  const [activeSection, setActiveSection] = useState("carreira");
  const [sectionCache, setSectionCache]   = useState({});
  const [loadingSection, setLoadingSection] = useState(false);
  const [loadingSugg, setLoadingSugg]     = useState(false);
  const [error, setError]                 = useState(null);
  const [typing, setTyping]               = useState(false);
  const debouncedQuery = useDebounce(query, 280);
  const t = UI_TEXT[lang];
  const { user, logout, canSearch, searchesLeft, updateSearchCount } = useAuth();
  const [showLogin, setShowLogin] = useState(false);
  const [showRegister, setShowRegister] = useState(false);
  const [showUpgrade, setShowUpgrade] = useState(false);

  useEffect(() => {
    api.getTrending().then(r => setTrending(r.data || [])).catch(() => {});
  }, []);

  useEffect(() => {
    if (debouncedQuery.length < 2) { setSuggestions([]); return; }
    setLoadingSugg(true);
    api.searchPoliticians(debouncedQuery, countryFilter)
      .then(r => setSuggestions(r.data || []))
      .catch(() => setSuggestions([]))
      .finally(() => setLoadingSugg(false));
  }, [debouncedQuery, countryFilter]);

  useEffect(() => {
    if (politician) setSectionCache({});
  }, [lang]);

  const loadSectionFor = useCallback(async (pol, section) => {
    const cacheKey = section + "_" + lang;
    if (sectionCache[cacheKey]) { setActiveSection(section); return; }
    if (!user) { setShowLogin(true); return; }
    if (!canSearch()) {
      setError(lang === "pt"
        ? "Voce usou suas 3 buscas gratuitas este mes. Clique em ASSINAR PRO para acesso ilimitado!"
        : "You used your 3 free searches this month. Click SUBSCRIBE PRO for unlimited access!");
      setShowUpgrade(true);
      return;
    }
    setLoadingSection(true);
    setActiveSection(section);
    setError(null);
    setTyping(false);
    try {
      const res = await api.getSection(pol.slug, section, lang);
      setSectionCache(prev => ({ ...prev, [cacheKey]: res.data }));
      setTyping(true);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoadingSection(false);
    }
  }, [lang, sectionCache]);

  const selectPolitician = useCallback((p) => {
    setPolitician(p);
    setQuery(p.full_name);
    setSuggestions([]);
    setSectionCache({});
    setActiveSection("carreira");
    setError(null);
    api.logSearch(p.full_name, p.id, 1);
    loadSectionFor(p, "carreira");
  }, [lang, loadSectionFor]);

  const loadSection = useCallback((section) => {
    if (!politician) return;
    loadSectionFor(politician, section);
  }, [politician, loadSectionFor]);

  const cacheKey = activeSection + "_" + lang;
  const current = sectionCache[cacheKey];
return (
    <>
      <style>{CSS}</style>
      <div className="app">
        <div className="bg-grid" />

        <header className="header">
          <div className="header-eyebrow">{t.eyebrow}</div>
          <h1>{t.title}<em>{t.titleAccent}</em></h1>
          <p className="header-sub">{t.subtitle}</p>
<div className="user-bar">
            {user ? (
              <>
                <span className="user-name">Ola, {user.name}</span>
                {!user.is_pro && (
                  <span className="searches-left">
                    {searchesLeft()} {lang === "pt" ? "buscas restantes" : "searches left"}
                  </span>
                )}
                {user.is_pro && <span className="pro-badge">PRO</span>}
                <button className="logout-btn" onClick={logout}>
                  {lang === "pt" ? "Sair" : "Logout"}
                </button>
              </>
            ) : (
              <>
                <button className="login-btn" onClick={() => setShowLogin(true)}>
                  {lang === "pt" ? "Entrar" : "Login"}
                </button>
                <button className="register-btn" onClick={() => setShowRegister(true)}>
                  {lang === "pt" ? "Cadastrar gratis" : "Sign up free"}
                </button>
              </>
            )}
          </div>

          <div className="lang-toggle">
            <button className={"lang-btn" + (lang === "pt" ? " active" : "")} onClick={() => setLang("pt")}>BR PT</button>
            <button className={"lang-btn" + (lang === "en" ? " active" : "")} onClick={() => setLang("en")}>US EN</button>
          </div>

          <div className="search-wrap">
            <div className="country-filter-row">
              {["", "BR", "US", "IL", "GB", "FR", "DE", "AR", "RU"].map(code => (
                <button key={code}
                  className={"country-chip" + (countryFilter === code ? " active" : "")}
                  onClick={() => setCountryFilter(code)}>
                  {code ? code : t.allCountries}
                </button>
              ))}
            </div>

            <div className={"search-box" + (suggestions.length ? " open" : "")}>
              <span className="search-icon">[ ]</span>
              <input
                className="search-input"
                placeholder={t.placeholder}
                value={query}
                onChange={e => setQuery(e.target.value)}
                autoComplete="off" spellCheck="false"
              />
              {loadingSugg && <span className="search-spinner" />}
            </div>

            {suggestions.length > 0 && (
              <div className="suggestions">
                {suggestions.map(p => (
                  <button key={p.id} className="suggestion-item" onClick={() => selectPolitician(p)}>
                    <span className="sug-flag">{COUNTRY_FLAGS[p.country_code] || "??"}</span>
                    <span className="sug-info">
                      <span className="sug-name">{p.full_name}</span>
                      <span className="sug-meta">{p.role} - {p.country}</span>
                    </span>
                    <span className="sug-party">{p.party}</span>
                  </button>
                ))}
              </div>
            )}
          </div>
        </header>

        {!politician && trending.length > 0 && (
          <section className="trending">
            <div className="trending-label">{t.trending}</div>
            <div className="trending-list">
              {trending.map(p => (
                <button key={p.slug} className="trending-chip" onClick={() => selectPolitician(p)}>
                  {COUNTRY_FLAGS[p.country_code] || "??"} {p.full_name} <span>{p.party}</span>
                </button>
              ))}
            </div>
          </section>
        )}

        {politician && (
          <main className="main">
            <div className="pol-header">
              <div className="pol-avatar">{politician.full_name[0]}</div>
              <div className="pol-info">
                <h2>{politician.full_name}</h2>
                <div className="pol-badges">
                  <span className="badge badge-party">{politician.party}</span>
                  {politician.state && politician.state !== "-" && (
                    <span className="badge badge-state">{politician.state}</span>
                  )}
                  <span className="badge badge-country">{politician.country}</span>
                  <span className="badge badge-role">{politician.role}</span>
                </div>
              </div>
            </div>

            <nav className="tabs">
              {SECTIONS.map(s => {
                const ck = s.key + "_" + lang;
                return (
                  <button key={s.key}
                    className={"tab" + (activeSection === s.key ? " active" : "")}
                    onClick={() => loadSection(s.key)}>
                    {s.icon} {s.label[lang]}
                    {sectionCache[ck] && <span className="tab-dot" />}
                  </button>
                );
              })}
            </nav>

            <div className="panel">
              <div className="panel-head">
                <span className="panel-title">
                  {SECTIONS.find(s => s.key === activeSection) && SECTIONS.find(s => s.key === activeSection).icon}{" "}
                  {SECTIONS.find(s => s.key === activeSection) && SECTIONS.find(s => s.key === activeSection).label[lang]}
                  {current && current.meta && current.meta.cached && <span className="cache-tag">{t.cached}</span>}
                </span>
                <span className="panel-model">{t.model}</span>
              </div>

              <div className="panel-body">
                {loadingSection ? (
                  <div className="state-loading">
                    <div className="spinner" />
                    <div className="loading-text">{t.loading}</div>
                  </div>
                ) : error ? (
                  <div className="state-error"><div>[!]</div><div>{error}</div></div>
                ) : current ? (
                  <div>
                    <div className="ai-text">
                      {typing
                        ? <TypewriterText text={current.ai_response} onDone={() => setTyping(false)} />
                        : current.ai_response}
                    </div>
                    {current.legal_records && current.legal_records.length > 0 && (
                      <div className="legal-records">
                        <div className="legal-records-title">{t.legalFound}</div>
                        {current.legal_records.map((r, i) => (
                          <div key={i} className={"legal-item legal-item--" + r.status}>
                            <div className="legal-item-head">
                              <span className="legal-badge">{r.type.replace(/_/g, " ").toUpperCase()}</span>
                              <span className="legal-court">{r.court}</span>
                              {r.year && <span className="legal-year">{r.year}</span>}
                            </div>
                            <div className="legal-subject">{r.subject}</div>
                            {r.source_url && r.source_url !== "#" && (
                              <a href={r.source_url} target="_blank" rel="noopener noreferrer" className="legal-link">
                                {lang === "en" ? "View official source" : "Ver fonte oficial"}
                              </a>
                            )}
                          </div>
                        ))}
                      </div>
                    )}
                    {current.external_links && current.external_links.length > 0 && (
                      <div className="external-links">
                        <div className="external-links-title">{t.officialLinks}</div>
                        <div className="external-links-grid">
                          {current.external_links.map((l, i) => (
                            <a key={i} href={l.url} target="_blank" rel="noopener noreferrer" className="ext-link-card">
                              <span className="ext-link-label">{l.label}</span>
                              <span className="ext-link-desc">{l.description}</span>
                            </a>
                          ))}
                        </div>
                      </div>
                    )}
                    {current.public_data && current.public_data.length > 0 && (
                      <div className="public-data">
                        <div className="public-data-title">{t.officialData}</div>
                        {current.public_data.map((d, i) => (
                          <div key={i} className="public-data-item">
                            <span className="pd-source">{d.source}</span>
                            <span className="pd-title">{d.title}</span>
                            {d.reference_date && <span className="pd-date">{new Date(d.reference_date).getFullYear()}</span>}
                          </div>
                        ))}
                      </div>
                    )}
                  </div>
                ) : (
                  <div className="state-empty">
                    <div className="empty-icon">[?]</div>
                    <p>{t.emptyTitle}</p>
                  </div>
                )}
              </div>

              {current && (
                <div className="panel-footer">
                  <span>{t.sources}</span>
                  {["TSE", "Camara", "Congress.gov", "Knesset", "TCU", "STF"].map(s => (
                    <span key={s} className="source-chip">{s}</span>
                  ))}
                  {current.meta && <span className="meta-tokens">{current.meta.tokens} {t.tokens}</span>}
                </div>
              )}
            </div>
          </main>
        )}

        {!politician && (
          <div className="empty-hero">
            <div className="empty-hero-icon">[*]</div>
            <h3>{t.heroTitle}</h3>
            <p>{t.heroSub}</p>
          </div>
        )}

        <footer className="footer">{t.disclaimer}</footer>
        {showUpgrade && (
          <div style={{position:"fixed",inset:0,background:"rgba(5,8,15,0.95)",display:"flex",alignItems:"center",justifyContent:"center",zIndex:1000,fontFamily:"'JetBrains Mono',monospace"}}>
            <div style={{background:"#0d1117",border:"1px solid rgba(255,255,255,0.08)",borderRadius:16,padding:"2.5rem",width:"100%",maxWidth:400,display:"flex",flexDirection:"column",gap:"1rem",textAlign:"center"}}>
              <div style={{fontSize:"2rem"}}>🔒</div>
              <h2 style={{fontFamily:"'DM Serif Display',serif",color:"#fff",margin:0}}>
                Limite atingido
              </h2>
              <p style={{color:"#4a5568",fontSize:"0.75rem",margin:0}}>
                Voce usou suas 3 buscas gratuitas deste mes.
              </p>
              <div style={{background:"rgba(240,180,41,0.05)",border:"1px solid rgba(240,180,41,0.2)",borderRadius:8,padding:"1rem"}}>
                <p style={{color:"#f0b429",fontSize:"0.8rem",fontWeight:"bold",margin:"0 0 0.5rem"}}>Plano Pro — R$ 19,99/mes</p>
                <p style={{color:"#4a5568",fontSize:"0.7rem",margin:0}}>Buscas ilimitadas + todos os paises</p>
              </div>
              <a href="https://pay.hotmart.com/R106351026S" target="_blank" rel="noopener noreferrer"
                style={{background:"linear-gradient(135deg,#f0b429,#ff6b35)",border:"none",borderRadius:8,padding:"0.9rem",color:"#000",fontWeight:700,fontSize:"0.9rem",cursor:"pointer",textDecoration:"none",display:"block"}}>
                Assinar Pro agora
              </a>
              <button onClick={() => setShowUpgrade(false)}
                style={{background:"transparent",border:"1px solid rgba(255,255,255,0.08)",borderRadius:8,padding:"0.6rem",color:"#4a5568",fontSize:"0.75rem",cursor:"pointer"}}>
                Fechar
              </button>
            </div>
          </div>
        )}
        {showLogin && (
          <Login
            onSwitchToRegister={() => { setShowLogin(false); setShowRegister(true); }}
            onSuccess={() => setShowLogin(false)}
          />
        )}
        {showRegister && (
          <Register
            onSwitchToLogin={() => { setShowRegister(false); setShowLogin(true); }}
            onSuccess={() => setShowRegister(false)}
          />
        )}
      </div>
    </>
  );
}
const CSS = `
@import url('https://fonts.googleapis.com/css2?family=DM+Serif+Display:ital@0;1&family=JetBrains+Mono:wght@300;400;500&display=swap');
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
:root { --bg: #05080f; --s1: #0d1117; --s2: #161c27; --border: rgba(255,255,255,0.06); --green: #00d97e; --amber: #f0b429; --blue: #4f8ef7; --red: #ff5c5c; --text: #dce6f0; --muted: #4a5568; --font-display: 'DM Serif Display', serif; --font-mono: 'JetBrains Mono', monospace; }
body { background: var(--bg); color: var(--text); font-family: var(--font-mono); font-size: 14px; line-height: 1.6; }
.app { min-height: 100vh; position: relative; overflow-x: hidden; }
.bg-grid { position: fixed; inset: 0; background-image: linear-gradient(rgba(79,142,247,0.03) 1px, transparent 1px), linear-gradient(90deg, rgba(79,142,247,0.03) 1px, transparent 1px); background-size: 40px 40px; pointer-events: none; z-index: 0; }
.header { position: relative; z-index: 10; text-align: center; padding: 3rem 1.5rem 2rem; background: radial-gradient(ellipse 70% 60% at 50% 0%, rgba(79,142,247,0.08) 0%, transparent 70%); }
.header-eyebrow { font-size: 0.6rem; letter-spacing: 0.35em; color: var(--green); text-transform: uppercase; margin-bottom: 1rem; }
.header h1 { font-family: var(--font-display); font-size: clamp(2.8rem, 7vw, 5rem); line-height: 1; color: #fff; margin-bottom: 0.75rem; }
.header h1 em { font-style: italic; background: linear-gradient(135deg, var(--amber) 0%, #ff6b35 100%); -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text; }
.header-sub { font-size: 0.68rem; color: var(--muted); letter-spacing: 0.06em; margin-bottom: 1.5rem; }
.lang-toggle { display: flex; gap: 0.4rem; justify-content: center; margin-bottom: 1.25rem; }
.lang-btn { padding: 0.3rem 0.85rem; background: var(--s1); border: 1px solid var(--border); border-radius: 99px; font-family: var(--font-mono); font-size: 0.7rem; color: var(--muted); cursor: pointer; transition: all 0.15s; }
.lang-btn.active { background: rgba(240,180,41,0.12); border-color: rgba(240,180,41,0.35); color: var(--amber); }
.search-wrap { max-width: 640px; margin: 0 auto; position: relative; }
.country-filter-row { display: flex; gap: 0.35rem; flex-wrap: wrap; justify-content: center; margin-bottom: 0.75rem; }
.country-chip { padding: 0.25rem 0.65rem; background: var(--s1); border: 1px solid var(--border); border-radius: 99px; font-family: var(--font-mono); font-size: 0.65rem; color: var(--muted); cursor: pointer; transition: all 0.15s; }
.country-chip.active { background: rgba(79,142,247,0.12); border-color: rgba(79,142,247,0.35); color: var(--blue); }
.search-box { display: flex; align-items: center; background: var(--s1); border: 1px solid var(--border); border-radius: 10px; transition: border-color 0.2s; }
.search-box:focus-within { border-color: rgba(79,142,247,0.4); box-shadow: 0 0 0 3px rgba(79,142,247,0.07); }
.search-icon { padding: 0 1rem 0 1.25rem; color: var(--muted); font-size: 0.8rem; }
.search-input { flex: 1; background: transparent; border: none; outline: none; padding: 0.9rem 0; font-family: var(--font-mono); font-size: 0.85rem; color: var(--text); caret-color: var(--amber); }
.search-input::placeholder { color: var(--muted); }
.search-spinner { width: 16px; height: 16px; border: 2px solid var(--border); border-top-color: var(--amber); border-radius: 50%; animation: spin 0.7s linear infinite; margin-right: 1rem; flex-shrink: 0; }
@keyframes spin { to { transform: rotate(360deg); } }
.suggestions { position: absolute; top: calc(100% + 6px); left: 0; right: 0; background: var(--s1); border: 1px solid var(--border); border-radius: 10px; z-index: 200; overflow: hidden; box-shadow: 0 24px 60px rgba(0,0,0,0.6); }
.suggestion-item { width: 100%; display: flex; align-items: center; gap: 0.85rem; padding: 0.75rem 1.1rem; background: none; border: none; border-bottom: 1px solid var(--border); cursor: pointer; transition: background 0.15s; text-align: left; }
.suggestion-item:last-child { border-bottom: none; }
.suggestion-item:hover { background: var(--s2); }
.sug-flag { font-size: 0.75rem; font-weight: bold; color: var(--blue); flex-shrink: 0; min-width: 24px; }
.sug-info { flex: 1; min-width: 0; }
.sug-name { display: block; font-size: 0.82rem; color: var(--text); font-weight: 500; }
.sug-meta { display: block; font-size: 0.65rem; color: var(--muted); margin-top: 0.1rem; }
.sug-party { padding: 0.15rem 0.5rem; background: rgba(240,180,41,0.1); border: 1px solid rgba(240,180,41,0.2); border-radius: 4px; font-size: 0.62rem; color: var(--amber); flex-shrink: 0; }
.trending { position: relative; z-index: 5; text-align: center; padding: 0 1.5rem 3rem; }
.trending-label { font-size: 0.65rem; letter-spacing: 0.15em; color: var(--muted); text-transform: uppercase; margin-bottom: 1rem; }
.trending-list { display: flex; gap: 0.5rem; flex-wrap: wrap; justify-content: center; }
.trending-chip { padding: 0.35rem 0.85rem; background: var(--s1); border: 1px solid var(--border); border-radius: 99px; font-family: var(--font-mono); font-size: 0.72rem; color: var(--text); cursor: pointer; transition: all 0.15s; display: flex; align-items: center; gap: 0.4rem; }
.trending-chip span { color: var(--muted); font-size: 0.62rem; }
.trending-chip:hover { border-color: rgba(79,142,247,0.35); color: var(--blue); }
.main { position: relative; z-index: 5; max-width: 820px; margin: 0 auto; padding: 0 1.5rem 3rem; animation: fadeUp 0.35s ease; }
@keyframes fadeUp { from { opacity: 0; transform: translateY(14px); } to { opacity: 1; transform: translateY(0); } }
.pol-header { display: flex; align-items: center; gap: 1.25rem; background: var(--s1); border: 1px solid var(--border); border-radius: 14px; padding: 1.5rem; margin-bottom: 1.25rem; }
.pol-avatar { width: 56px; height: 56px; background: linear-gradient(135deg, var(--blue), var(--amber)); border-radius: 50%; display: flex; align-items: center; justify-content: center; font-family: var(--font-display); font-size: 1.6rem; color: #000; flex-shrink: 0; }
.pol-info { flex: 1; }
.pol-info h2 { font-family: var(--font-display); font-size: 1.4rem; color: #fff; margin-bottom: 0.4rem; }
.pol-badges { display: flex; gap: 0.4rem; flex-wrap: wrap; }
.badge { padding: 0.18rem 0.55rem; border-radius: 4px; font-size: 0.62rem; letter-spacing: 0.06em; font-weight: 500; }
.badge-party { background: rgba(240,180,41,0.1); border: 1px solid rgba(240,180,41,0.22); color: var(--amber); }
.badge-state { background: rgba(79,142,247,0.1); border: 1px solid rgba(79,142,247,0.22); color: var(--blue); }
.badge-country { background: rgba(0,217,126,0.08); border: 1px solid rgba(0,217,126,0.2); color: var(--green); }
.badge-role { background: rgba(255,255,255,0.04); border: 1px solid var(--border); color: var(--muted); }
.tabs { display: flex; gap: 0.4rem; margin-bottom: 1.25rem; overflow-x: auto; scrollbar-width: none; padding-bottom: 2px; }
.tabs::-webkit-scrollbar { display: none; }
.tab { display: flex; align-items: center; gap: 0.35rem; padding: 0.5rem 1rem; background: var(--s1); border: 1px solid var(--border); border-radius: 8px; font-family: var(--font-mono); font-size: 0.72rem; color: var(--muted); cursor: pointer; white-space: nowrap; transition: all 0.15s; }
.tab:hover { border-color: rgba(255,255,255,0.12); color: var(--text); }
.tab.active { background: rgba(79,142,247,0.1); border-color: rgba(79,142,247,0.35); color: var(--blue); }
.tab-dot { width: 5px; height: 5px; background: var(--green); border-radius: 50%; box-shadow: 0 0 6px var(--green); }
.panel { background: var(--s1); border: 1px solid var(--border); border-radius: 14px; overflow: hidden; }
.panel-head { display: flex; align-items: center; justify-content: space-between; padding: 1rem 1.5rem; border-bottom: 1px solid var(--border); background: var(--s2); }
.panel-title { font-size: 0.8rem; font-weight: 500; display: flex; align-items: center; gap: 0.5rem; }
.cache-tag { padding: 0.1rem 0.4rem; background: rgba(0,217,126,0.1); border: 1px solid rgba(0,217,126,0.2); border-radius: 3px; font-size: 0.55rem; color: var(--green); }
.panel-model { font-size: 0.62rem; color: var(--muted); }
.panel-body { padding: 1.5rem; min-height: 260px; }
.ai-text { font-size: 0.82rem; line-height: 1.9; color: #b8c9d9; white-space: pre-wrap; }
.legal-records { margin-top: 1.5rem; padding-top: 1.5rem; border-top: 1px solid var(--border); }
.legal-records-title { font-size: 0.68rem; letter-spacing: 0.1em; color: var(--muted); text-transform: uppercase; margin-bottom: 0.85rem; }
.legal-item { padding: 0.85rem 1rem; border-radius: 8px; margin-bottom: 0.5rem; border: 1px solid var(--border); background: rgba(255,255,255,0.02); }
.legal-item--condenado,.legal-item--inelegibilidade { border-color: rgba(255,92,92,0.2); background: rgba(255,92,92,0.04); }
.legal-item--verificar { border-color: rgba(240,180,41,0.15); background: rgba(240,180,41,0.03); }
.legal-item-head { display: flex; align-items: center; gap: 0.5rem; flex-wrap: wrap; margin-bottom: 0.4rem; }
.legal-badge { padding: 0.15rem 0.5rem; border-radius: 4px; font-size: 0.58rem; font-weight: 600; background: rgba(79,142,247,0.1); border: 1px solid rgba(79,142,247,0.25); color: var(--blue); }
.legal-court { font-size: 0.65rem; color: var(--muted); }
.legal-year { font-size: 0.62rem; color: var(--muted); margin-left: auto; }
.legal-subject { font-size: 0.75rem; color: #b8c9d9; line-height: 1.6; margin-bottom: 0.35rem; }
.legal-link { font-size: 0.62rem; color: var(--blue); text-decoration: none; }
.external-links { margin-top: 1.25rem; padding-top: 1.25rem; border-top: 1px solid var(--border); }
.external-links-title { font-size: 0.68rem; letter-spacing: 0.1em; color: var(--muted); text-transform: uppercase; margin-bottom: 0.75rem; }
.external-links-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(210px, 1fr)); gap: 0.5rem; }
.ext-link-card { display: flex; flex-direction: column; gap: 0.2rem; padding: 0.75rem 0.9rem; background: var(--s2); border: 1px solid var(--border); border-radius: 8px; text-decoration: none; transition: border-color 0.15s; }
.ext-link-card:hover { border-color: rgba(79,142,247,0.3); }
.ext-link-label { font-size: 0.72rem; color: var(--text); font-weight: 500; }
.ext-link-desc { font-size: 0.62rem; color: var(--muted); line-height: 1.4; }
.public-data { margin-top: 1.5rem; padding-top: 1.5rem; border-top: 1px solid var(--border); }
.public-data-title { font-size: 0.68rem; letter-spacing: 0.1em; color: var(--muted); text-transform: uppercase; margin-bottom: 0.75rem; }
.public-data-item { display: flex; align-items: center; gap: 0.75rem; padding: 0.5rem 0; border-bottom: 1px solid var(--border); font-size: 0.72rem; }
.public-data-item:last-child { border-bottom: none; }
.pd-source { padding: 0.1rem 0.4rem; background: rgba(79,142,247,0.1); border: 1px solid rgba(79,142,247,0.2); border-radius: 3px; font-size: 0.6rem; color: var(--blue); flex-shrink: 0; }
.pd-title { flex: 1; color: var(--text); }
.pd-date { color: var(--muted); flex-shrink: 0; }
.panel-footer { display: flex; align-items: center; gap: 0.5rem; flex-wrap: wrap; padding: 0.85rem 1.5rem; border-top: 1px solid var(--border); background: var(--s2); font-size: 0.62rem; color: var(--muted); }
.source-chip { padding: 0.1rem 0.45rem; background: rgba(255,255,255,0.03); border: 1px solid var(--border); border-radius: 3px; color: var(--muted); }
.meta-tokens { margin-left: auto; color: var(--muted); font-size: 0.58rem; }
.state-loading { display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 1.25rem; padding: 3rem; }
.spinner { width: 36px; height: 36px; border: 2px solid var(--border); border-top-color: var(--amber); border-radius: 50%; animation: spin 0.7s linear infinite; }
.loading-text { font-size: 0.7rem; color: var(--muted); letter-spacing: 0.1em; animation: blink 1.5s ease infinite; }
@keyframes blink { 0%,100%{opacity:.4} 50%{opacity:1} }
.state-error { display: flex; align-items: center; gap: 1rem; padding: 2rem; color: var(--red); font-size: 0.8rem; }
.state-empty { display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 0.75rem; padding: 3rem; text-align: center; }
.empty-icon { font-size: 2rem; opacity: 0.2; }
.state-empty p { font-size: 0.75rem; color: var(--muted); }
.empty-hero { position: relative; z-index: 5; text-align: center; padding: 4rem 1.5rem; }
.empty-hero-icon { font-size: 2rem; margin-bottom: 1rem; opacity: 0.3; }
.empty-hero h3 { font-family: var(--font-display); font-size: 1.6rem; color: var(--muted); margin-bottom: 0.75rem; }
.empty-hero p { font-size: 0.75rem; color: var(--muted); opacity: 0.6; line-height: 1.8; }
.user-bar { display: flex; align-items: center; gap: 0.75rem; justify-content: center; flex-wrap: wrap; margin-bottom: 1rem; }
.user-name { font-size: 0.72rem; color: #dce6f0; }
.searches-left { font-size: 0.65rem; color: #f0b429; background: rgba(240,180,41,0.1); border: 1px solid rgba(240,180,41,0.2); padding: 0.2rem 0.6rem; border-radius: 99px; }
.pro-badge { font-size: 0.65rem; color: #00d97e; background: rgba(0,217,126,0.1); border: 1px solid rgba(0,217,126,0.2); padding: 0.2rem 0.6rem; border-radius: 99px; letter-spacing: 0.1em; }
.logout-btn { padding: 0.25rem 0.75rem; background: rgba(255,92,92,0.1); border: 1px solid rgba(255,92,92,0.2); border-radius: 6px; color: #ff5c5c; font-family: 'JetBrains Mono', monospace; font-size: 0.65rem; cursor: pointer; }
.login-btn { padding: 0.3rem 0.85rem; background: rgba(79,142,247,0.1); border: 1px solid rgba(79,142,247,0.25); border-radius: 99px; color: #4f8ef7; font-family: 'JetBrains Mono', monospace; font-size: 0.7rem; cursor: pointer; }
.register-btn { padding: 0.3rem 0.85rem; background: linear-gradient(135deg, #f0b429, #ff6b35); border: none; border-radius: 99px; color：#000; font-family: 'JetBrains Mono', monospace; font-size：#ff6b35; font-weight：700; cursor：pointer; }
.footer { text-align: center; padding: 2rem; font-size: 0.62rem; color: var(--muted); opacity: 0.5; position: relative; z-index: 5; }
.cursor { display: inline-block; width: 7px; height: 13px; background: var(--amber); margin-left: 2px; vertical-align: middle; animation: blink2 1s step-end infinite; border-radius: 1px; }
@keyframes blink2 { 0%,100%{opacity:1} 50%{opacity:0} }
@media (max-width: 600px) { .pol-header { flex-direction: column; text-align: center; } .pol-badges { justify-content: center; } }
`;